import Head from 'next/head'
import Image from 'next/image'
import Faq from 'react-faq-component'

import styles from '../styles/Home.module.css'
import InfoItem from 'components/InfoItem'
import LeadForm from 'components/LeadForm'
import HeroSection from 'components/HeroSection'
import faqData from './faq_data.js'
import featureBlob1 from 'assets/feature_blob_1.svg'
import featureBlob2 from 'assets/feature_blob_2.svg'
import featureBlob3 from 'assets/feature_blob_3.svg'
import featureBlob4 from 'assets/feature_blob_4.svg'
import featureBlob5 from 'assets/feature_blob_5.svg'
import featureBlob6 from 'assets/feature_blob_6.svg'
import heroImage from 'assets/hero_image_01.png'
import acIcon from 'assets/air-conditioning.png'
import cctvIcon from 'assets/cctv-camera.png'
import downloadIcon from 'assets/download.png'
import carIcon from 'assets/garage.png'
import cabinIcon from 'assets/incognito.png'
import emergencyIcon from 'assets/emergency-call.png'
import videoIcon from 'assets/video-camera.png'
import callIcon from 'assets/phone-call.png'
import ballIcon from 'assets/fitness-ball.png'
import partyIcon from 'assets/party.png'
import location from 'assets/location.png'
import { benefits } from './data'
// import featureBlob6 from 'assets/feature_blob_6.svg'
// import featureBlob6 from 'assets/feature_blob_6.svg'

const faqStyles = {
  bgColor: 'transparent'
  // rowContentColor: 'grey',
  // arrowColor: "red",
}

const blobStyles = {
  egg: {
    position: 'absolute',
    left: 40,
    right: 0,
    bottom: 0,
    top: 44,
    justifyContent: 'center',
    alignItems: 'center'
  },
  shell: {
    position: 'absolute',
    left: 40,
    right: 0,
    bottom: 0,
    top: 28,
    justifyContent: 'center',
    alignItems: 'center'
  }
}

const BlobFeature = props => {
  return (
    <article
      style={{
        position: 'relative',
        minWidth: 200,
        width: '20%',
        marginRight: '5%',
        marginTop: 48,
        marginBottom: 48
      }}
    >
      <span style={{ fontSize: 20, textAlign: 'center', marginBottom: 24 }}>
        {props.title}
      </span>
      <img src={props.image?.src} />
      <article style={blobStyles[props.type]}>
        <span>{props.description}</span>
      </article>
    </article>
  )
}

const SmallFeatureItem = props => (
  <article
    className='row'
    style={{ alignItems: 'center', marginRight: 24, marginBottom: 12 }}
  >
    <article
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        height: 44,
        width: 44,
        overflow: 'hidden',
        borderRadius: 999,
        backgroundColor: 'white',
        border: '2px solid #c5cfd8'
      }}
    >
      <img src={props.icon?.src} style={{ width: 24, height: 24 }} />
    </article>
    <span>{props.label}</span>
  </article>
)

export default function Home () {
  return (
    <article className='flexBox'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <section className={`flexBox row`} style={{ height: '60vh' }}>
          <HeroSection />
        </section>
        <section className={`flexBox flex ${styles.section}`}>
          <span className={styles.title}>Services for every cat and dog</span>
          <article
            className='row'
            style={{
              alignSelf: 'center',
              flexWrap: 'wrap',
              justifyContent: 'center'
            }}
          >
            {benefits.map(benefit => (
              <BlobFeature
                type='egg'
                image={featureBlob1}
                key={benefit.title}
                title={benefit.title}
                description={benefit.description}
              />
            ))}
          </article>
        </section>
        <section className={`flexBox ${styles.section}`}>
          <span className={styles.title}>
            What people have to tell about us
          </span>
        </section>
        <section className={`flexBox ${styles.section}`}>
          <article className='row'>
            <article style={{ flex: 1, justifyContent: 'space-around' }}>
              <span style={{ marginBottom: 54, fontSize: 44, marginRight: 44 }}>
                How can we pamper your pet today?
              </span>
            </article>
            <LeadForm />
          </article>
        </section>
        <section className={`flexBox ${styles.section}`}>
          <span className={styles.title}>We take pet care very seriously</span>
          <article className='row'>
            <article>
              <SmallFeatureItem label='Air Conditioning' icon={acIcon} />
              <SmallFeatureItem label='24x7 CCTV' icon={cctvIcon} />
              <SmallFeatureItem label='Daily Updates' icon={downloadIcon} />
              <SmallFeatureItem label='Private Cabins' icon={cabinIcon} />
            </article>
            <article>
              <SmallFeatureItem label='Pick up & Drop' icon={carIcon} />
              <SmallFeatureItem label='On Call Vet' icon={emergencyIcon} />
              <SmallFeatureItem label='Video Callings' icon={videoIcon} />
            </article>
            <article className='flex' />

            <article
              style={{ height: 240, width: 240, backgroundColor: 'gray' }}
            />
          </article>
        </section>
        <section className={`flexBox ${styles.section}`}>
          <span className={styles.title}>The best choice for your Pooch</span>
          <article className='row' style={{ alignItems: 'center' }}>
            <article
              style={{
                flex: 1,
                justifyContent: 'space-around',
                marginRight: 48
              }}
            >
              <InfoItem
                icon={ballIcon}
                heading='FROM 8 AM TO 10 PM'
                description='Timings are drop off after 8am and collection is before 10am on the morning of going home.'
              />
              <InfoItem
                icon={partyIcon}
                heading='FAVORITES'
                description='If your dog has separation anxiety we encourage you to bring something that smells like home.'
              />
              <InfoItem
                icon={callIcon}
                heading='CONTACT US ON'
                description='axc@gfh.com | 9999999999'
              />
            </article>
            <img
              src={location.src}
              style={{ height: 320, width: 320, backgroundColor: 'gray' }}
            />
          </article>
        </section>
        <section className={`flexBox ${styles.section}`}>
          <Faq data={faqData} styles={faqStyles} />
        </section>
      </main>

      <footer className={styles.footer}>
        <article>
          <span>Follow #Pupstop : a pet boarding centre</span>
          <article className='row'>
            <article
              style={{
                marginRight: 12,
                height: 32,
                width: 32,
                backgroundColor: 'green'
              }}
            />
            <article
              style={{
                marginRight: 12,
                height: 32,
                width: 32,
                backgroundColor: 'green'
              }}
            />
          </article>
          <span style={{ marginTop: 24 }}>Working hours</span>
          <span>All days - 8:00 am to 10:00 pm</span>
        </article>

        <article>
          <span>Address</span>
          <span>Wadala truck terminal Gala no 14</span>
          <span>Plot C1, shram shakti society</span>
          <span>Mumbai, Maharashtra</span>
          <span>400037</span>
        </article>
      </footer>
    </article>
  )
}
